name: vktinder
description: A Flutter project for VK group users with tinder-like swiping.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  get: ^4.6.5

  # Local Storage
  get_storage: ^2.1.1
  shared_preferences: ^2.1.1

  # UI
  cupertino_icons: ^1.0.5
  flutter_spinkit: ^5.2.0

  dio: ^5.4.3+1
  mockingjay: ^1.0.0
  image_cache: ^1.0.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true